version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${FASTAPI_PORT:-8000}:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    # Enable hot reload
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000
    restart: always
    networks:
      - backend
  mcp:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    env_file:
      - .env
    command: poetry run uvicorn mcp_server.main:app --host 0.0.0.0 --port 8888 --timeout-graceful-shutdown 3
    networks:
      - backend

networks:
  backend:
    driver: bridge