version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${FASTAPI_PORT:-8000}:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    # Enable hot reload
    command: poetry run uvicorn server:app --host 0.0.0.0 --port 8000
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge